version: "3.9"

services:
  spring-metodos-numericos-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-metodos-numericos-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - spring-networks
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ./pom.xml:/app/pom.xml
    command: >
      sh -c "mvn clean package -DskipTests &&
             java -jar target/*.jar"

networks:
  spring-networks:
    driver: bridge
